name: trendyol-hackathon
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - polars
      - pyarrow
      - lightgbm
      - nbformat
      - nbclient
      - nbconvert
